# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2h1k6xJ-N7YuokUArxyRpzT-aldkgef
"""

name=["abinaya","deepika","monisha"]
name.append("akshaya")
marks=[80,90,70]
print(name)
print(marks[2])
print(len(name))
print(len(marks))

